# Generated by Django 4.1 on 2024-01-31 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('raza', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('duenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('duenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.cliente')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.perro')),
            ],
        ),
    ]
