# Generated by Django 4.1 on 2024-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(default='perros/default.png', upload_to='perros'),
            preserve_default=False,
        ),
    ]
